<?xml version="1.0" encoding="UTF-8"?><testrun name="HsqldbUserDaoTest" project="usermanagement171" tests="2" started="2" failures="0" errors="2" ignored="0">
  <testsuite name="ua.nure.cs.chebanenko.usermanagement171.db.HsqldbUserDaoTest" time="0.286">
    <testcase name="testFindAll" classname="ua.nure.cs.chebanenko.usermanagement171.db.HsqldbUserDaoTest" time="0.284">
      <error>org.dbunit.dataset.DataSetException: java.net.MalformedURLException&#13;
	at org.dbunit.dataset.xml.XmlProducer.produce(XmlProducer.java:125)&#13;
	at org.dbunit.dataset.CachedDataSet.&lt;init&gt;(CachedDataSet.java:71)&#13;
	at org.dbunit.dataset.xml.XmlDataSet.&lt;init&gt;(XmlDataSet.java:68)&#13;
	at ua.nure.cs.chebanenko.usermanagement171.db.HsqldbUserDaoTest.getDataSet(HsqldbUserDaoTest.java:61)&#13;
	at org.dbunit.DatabaseTestCase.executeOperation(DatabaseTestCase.java:87)&#13;
	at org.dbunit.DatabaseTestCase.setUp(DatabaseTestCase.java:104)&#13;
	at ua.nure.cs.chebanenko.usermanagement171.db.HsqldbUserDaoTest.setUp(HsqldbUserDaoTest.java:23)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:139)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:252)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:247)&#13;
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:124)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)&#13;
java.net.MalformedURLException&#13;
	at java.net.URL.&lt;init&gt;(Unknown Source)&#13;
	at java.net.URL.&lt;init&gt;(Unknown Source)&#13;
	at java.net.URL.&lt;init&gt;(Unknown Source)&#13;
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(Unknown Source)&#13;
	at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(Unknown Source)&#13;
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)&#13;
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)&#13;
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)&#13;
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)&#13;
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)&#13;
	at org.dbunit.dataset.xml.XmlProducer.produce(XmlProducer.java:112)&#13;
	at org.dbunit.dataset.CachedDataSet.&lt;init&gt;(CachedDataSet.java:71)&#13;
	at org.dbunit.dataset.xml.XmlDataSet.&lt;init&gt;(XmlDataSet.java:68)&#13;
	at ua.nure.cs.chebanenko.usermanagement171.db.HsqldbUserDaoTest.getDataSet(HsqldbUserDaoTest.java:61)&#13;
	at org.dbunit.DatabaseTestCase.executeOperation(DatabaseTestCase.java:87)&#13;
	at org.dbunit.DatabaseTestCase.setUp(DatabaseTestCase.java:104)&#13;
	at ua.nure.cs.chebanenko.usermanagement171.db.HsqldbUserDaoTest.setUp(HsqldbUserDaoTest.java:23)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:139)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:252)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:247)&#13;
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:124)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)&#13;
Caused by: java.lang.NullPointerException&#13;
	... 30 more&#13;
&#13;
</error>
    </testcase>
    <testcase name="testCreate" classname="ua.nure.cs.chebanenko.usermanagement171.db.HsqldbUserDaoTest" time="0.002">
      <error>org.dbunit.dataset.DataSetException: java.net.MalformedURLException&#13;
	at org.dbunit.dataset.xml.XmlProducer.produce(XmlProducer.java:125)&#13;
	at org.dbunit.dataset.CachedDataSet.&lt;init&gt;(CachedDataSet.java:71)&#13;
	at org.dbunit.dataset.xml.XmlDataSet.&lt;init&gt;(XmlDataSet.java:68)&#13;
	at ua.nure.cs.chebanenko.usermanagement171.db.HsqldbUserDaoTest.getDataSet(HsqldbUserDaoTest.java:61)&#13;
	at org.dbunit.DatabaseTestCase.executeOperation(DatabaseTestCase.java:87)&#13;
	at org.dbunit.DatabaseTestCase.setUp(DatabaseTestCase.java:104)&#13;
	at ua.nure.cs.chebanenko.usermanagement171.db.HsqldbUserDaoTest.setUp(HsqldbUserDaoTest.java:23)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:139)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:252)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:247)&#13;
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:124)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)&#13;
java.net.MalformedURLException&#13;
	at java.net.URL.&lt;init&gt;(Unknown Source)&#13;
	at java.net.URL.&lt;init&gt;(Unknown Source)&#13;
	at java.net.URL.&lt;init&gt;(Unknown Source)&#13;
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(Unknown Source)&#13;
	at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(Unknown Source)&#13;
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)&#13;
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)&#13;
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)&#13;
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)&#13;
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)&#13;
	at org.dbunit.dataset.xml.XmlProducer.produce(XmlProducer.java:112)&#13;
	at org.dbunit.dataset.CachedDataSet.&lt;init&gt;(CachedDataSet.java:71)&#13;
	at org.dbunit.dataset.xml.XmlDataSet.&lt;init&gt;(XmlDataSet.java:68)&#13;
	at ua.nure.cs.chebanenko.usermanagement171.db.HsqldbUserDaoTest.getDataSet(HsqldbUserDaoTest.java:61)&#13;
	at org.dbunit.DatabaseTestCase.executeOperation(DatabaseTestCase.java:87)&#13;
	at org.dbunit.DatabaseTestCase.setUp(DatabaseTestCase.java:104)&#13;
	at ua.nure.cs.chebanenko.usermanagement171.db.HsqldbUserDaoTest.setUp(HsqldbUserDaoTest.java:23)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:139)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:252)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:247)&#13;
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:124)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)&#13;
Caused by: java.lang.NullPointerException&#13;
	... 30 more&#13;
&#13;
</error>
    </testcase>
  </testsuite>
</testrun>
